### ISSUE TITLE
Support conditions in tags

### ISSUE THREAD

**Issue by ArtAndreev** [junk1tm/musttag#37]
I wanted to add `envconfig` tag as explicit tag required for function `Process`:

```yaml
- name: github.com/kelseyhightower/envconfig.Process
  tag: envconfig
  arg-pos: 1
```

As it stated in README.md, tag `ignored` is used, when field must not be processed.

So there is no way to define that either `envconfig` or `ignored` must be added to struct.
